// Configuration for WizGym Admin Dashboard - PRODUCTION
// Auto-generated by deploy.sh

window.WIZGYM_CONFIG = {
  cognito: {
    region: 'us-east-1',
    userPoolId: 'us-east-1_VSd5foNdB',
    clientId: '1ta05vq4df4in9bnuot076fkct',
    domain: 'wizgym-admin',
  },
  api: {
    baseUrl: '/api/v1',
  },
  features: {
    enableDevMode: false,
  },
};
