#!/bin/bash
# Production Deployment - iPhone Test

echo "📱 WizGym iPhone Deployment Guide"
echo "===================================="
echo ""
echo "✅ Backend Status: RUNNING"
echo "✅ AWS SSO: AUTHENTICATED"
echo "✅ OTP Test: SUCCESS (received: 907799)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 DEPLOYMENT STEPS"
echo ""
echo "1️⃣  Open Xcode Workspace"
echo "   cd /Users/ghaythallaheebi/WizGymProd/apps/mobile"
echo "   open ios/Runner.xcworkspace"
echo ""
echo "2️⃣  Select Your iPhone"
echo "   • Click device selector (top toolbar)"
echo "   • Choose: iPhone (00008150-001439D43C87801C)"
echo ""
echo "3️⃣  Build & Deploy"
echo "   • Click ▶️ (Run button)"
echo "   • Or: Product → Run (⌘R)"
echo "   • Wait for build (~2-3 minutes)"
echo ""
echo "4️⃣  Test on Device"
echo "   ┌──────────────────────────────────────────────┐"
echo "   │ Expected: New Neon Auth Entry Page          │"
echo "   ├──────────────────────────────────────────────┤"
echo "   │ • Gradient hero (lime/lavender/pink)        │"
echo "   │ • Pink \"إنشاء حساب\" button with glow       │"
echo "   │ • Lavender \"تسجيل الدخول\" button with neon │"
echo "   │ • Fitness icon, beautiful Arabic text       │"
echo "   └──────────────────────────────────────────────┘"
echo ""
echo "5️⃣  Test Auth Flow"
echo "   a) Tap \"Create Account\" (pink button)"
echo "   b) Select role (Trainee/Trainer/Owner)"
echo "   c) Enter phone: 07831367435"
echo "   d) Tap \"Send OTP\""
echo "   e) Enter OTP when received"
echo "   f) Set password"
echo "   g) Complete signup"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎨 NEW DESIGN FEATURES"
echo ""
echo "╔═══════════════════════════════════════════════════════╗"
echo "║  BEFORE: Plain black/green split, boring buttons     ║"
echo "║  AFTER:  Unified dark neon theme, all colors shine!  ║"
echo "╚═══════════════════════════════════════════════════════╝"
echo ""
echo "Hero Section:"
echo "  • Multi-color gradient background"
echo "  • Fitness dumbbell icon (lime)"
echo "  • Bold Arabic headline"
echo "  • Subtitle with context"
echo ""
echo "Create Account Button:"
echo "  • Pink → Pink gradient (#F0A8D0)"
echo "  • Glowing shadow (30% opacity)"
echo "  • Person add icon"
echo "  • Bold Arabic text"
echo ""
echo "Sign In Button:"
echo "  • Lavender border (#C4B5FD, 2px)"
echo "  • Transparent background"
echo "  • Glowing shadow (20% opacity)"
echo "  • Login icon"
echo "  • Bold Arabic text"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🐛 TROUBLESHOOTING"
echo ""
echo "❌ If you see the login form instead of entry page:"
echo "   → Tap the ← back arrow"
echo "   → Or: Kill and restart the app"
echo ""
echo "❌ If build fails in Xcode:"
echo "   → Product → Clean Build Folder (⌘⇧K)"
echo "   → Close Xcode"
echo "   → Run: flutter clean && flutter pub get"
echo "   → Reopen Xcode and try again"
echo ""
echo "❌ If OTP doesn't arrive:"
echo "   → Check Lambda logs: aws logs tail /aws/lambda/sam-app-WizGymApiFunction-yE1SQSAsdJGg --since 5m --profile wizgym-prod --region us-east-1"
echo "   → Ensure OTPIQ_API_KEY is in SSM: aws ssm get-parameter --name /wizgym/prod/OTPIQ_API_KEY --with-decryption --profile wizgym-prod --region us-east-1"
echo "   → Try again (rate limit: 45 seconds)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 BACKEND STATUS CHECK"
echo ""

# Check if AWS Lambda is reachable (the real backend)
if curl -sf "https://3u10v51mvk.execute-api.us-east-1.amazonaws.com/api/v1/gyms/public" > /dev/null 2>&1; then
  echo "✅ Backend: AWS Lambda responding"
else
  echo "⚠️  Backend: AWS Lambda not reachable (check AWS auth + network)"
  echo "   Login: aws sso login --profile wizgym-prod"
fi

# Check AWS authentication
if aws sts get-caller-identity --profile wizgym-prod > /dev/null 2>&1; then
  echo "✅ AWS SSO: Authenticated"
else
  echo "❌ AWS SSO: Not authenticated"
  echo "   Login: aws sso login --profile wizgym-prod"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 READY TO DEPLOY!"
echo ""
echo "Run this command to open Xcode:"
echo "  open /Users/ghaythallaheebi/WizGymProd/apps/mobile/ios/Runner.xcworkspace"
echo ""
echo "Then click ▶️ Run and test the beautiful new design on your iPhone!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
