#!/bin/bash
# Deploy WizGym Admin Dashboard to AWS S3 + CloudFront

set -e

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
S3_BUCKET="wizgym-admin-dashboard"
CLOUDFRONT_DISTRIBUTION_ID="${CLOUDFRONT_DISTRIBUTION_ID:-}" # Set via environment or replace
AWS_REGION="${AWS_REGION:-us-east-1}"
COGNITO_USER_POOL_ID="${COGNITO_USER_POOL_ID:-}"
COGNITO_CLIENT_ID="${COGNITO_CLIENT_ID:-}"

echo -e "${BLUE}🚀 WizGym Admin Dashboard Deployment${NC}"
echo "======================================"

# Check required environment variables
if [ -z "$COGNITO_USER_POOL_ID" ] || [ -z "$COGNITO_CLIENT_ID" ]; then
  echo -e "${RED}❌ Error: COGNITO_USER_POOL_ID and COGNITO_CLIENT_ID must be set${NC}"
  echo "Example:"
  echo "  export COGNITO_USER_POOL_ID=us-east-1_YourPoolId"
  echo "  export COGNITO_CLIENT_ID=YourClientId"
  exit 1
fi

# Navigate to dashboard directory
cd "$(dirname "$0")"

# Update config.js with production values
echo -e "${BLUE}📝 Updating config.js with production values...${NC}"
cat > config.js << EOF
// Configuration for WizGym Admin Dashboard - PRODUCTION
// Auto-generated by deploy.sh

window.WIZGYM_CONFIG = {
  cognito: {
    region: '${AWS_REGION}',
    userPoolId: '${COGNITO_USER_POOL_ID}',
    clientId: '${COGNITO_CLIENT_ID}',
    domain: 'wizgym-admin',
  },
  api: {
    baseUrl: '/api/v1',
  },
  features: {
    enableDevMode: false,
  },
};
EOF

echo -e "${GREEN}✅ Config updated${NC}"

# Create S3 bucket if it doesn't exist
echo -e "${BLUE}📦 Checking S3 bucket...${NC}"
if ! aws s3 ls "s3://${S3_BUCKET}" 2>&1 >/dev/null; then
  echo "Creating bucket ${S3_BUCKET}..."
  aws s3 mb "s3://${S3_BUCKET}" --region "${AWS_REGION}"
  
  # Enable website hosting
  aws s3 website "s3://${S3_BUCKET}" \
    --index-document index.html \
    --error-document index.html
  
  echo -e "${GREEN}✅ Bucket created${NC}"
else
  echo -e "${GREEN}✅ Bucket exists${NC}"
fi

# Sync files to S3
echo -e "${BLUE}📤 Uploading files to S3...${NC}"
aws s3 sync . "s3://${S3_BUCKET}/" \
  --exclude "*.md" \
  --exclude ".git/*" \
  --exclude ".gitignore" \
  --exclude "deploy.sh" \
  --exclude ".DS_Store" \
  --cache-control "public,max-age=31536000" \
  --region "${AWS_REGION}"

# Set correct cache for HTML files (shorter cache)
aws s3 cp index.html "s3://${S3_BUCKET}/index.html" \
  --cache-control "no-cache" \
  --content-type "text/html" \
  --region "${AWS_REGION}"

aws s3 cp login.html "s3://${S3_BUCKET}/login.html" \
  --cache-control "no-cache" \
  --content-type "text/html" \
  --region "${AWS_REGION}"

echo -e "${GREEN}✅ Files uploaded${NC}"

# Invalidate CloudFront cache if distribution ID is provided
if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
  echo -e "${BLUE}🔄 Invalidating CloudFront cache...${NC}"
  aws cloudfront create-invalidation \
    --distribution-id "${CLOUDFRONT_DISTRIBUTION_ID}" \
    --paths "/*"
  echo -e "${GREEN}✅ Cache invalidated${NC}"
else
  echo -e "${BLUE}ℹ️  No CloudFront distribution ID provided, skipping cache invalidation${NC}"
fi

echo ""
echo -e "${GREEN}✨ Deployment complete!${NC}"
echo ""
echo "Admin Dashboard URL:"
if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
  echo "  https://admin.wizgym.app (or your CloudFront domain)"
else
  echo "  http://${S3_BUCKET}.s3-website-${AWS_REGION}.amazonaws.com"
fi
echo ""
echo "First time setup:"
echo "  1. Create admin user in Cognito"
echo "  2. Add user to 'superadmins' group"
echo "  3. Login at the dashboard URL above"
echo ""
